MusicRepo/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MusicRepo.Models
{
    public class AlbumsController : Controller
    {
        private visualStudioDBEntities db = new visualStudioDBEntities();

        // GET: Albums
        public ActionResult Index(String sortOrder, String searchString)
        {
            ViewBag.NomeSortParm = sortOrder == "Nome" ? "nome_desc" : "Nome";
            ViewBag.AnoSortParm = sortOrder == "Ano" ? "ano_desc" : "Ano";
            ViewBag.ArtistaSortParm = sortOrder == "Artista" ? "artista_desc" : "Artista";
            ViewBag.EditoraSortParm = sortOrder == "Editora" ? "editora_desc" : "Editora";
            var albums = from s in db.Albums
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                albums = albums.Where(s => s.Nome.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "Nome":
                    albums = albums.OrderBy(s => s.Nome);
                    break;
                case "nome_desc":
                    albums = albums.OrderByDescending(s => s.Nome);
                    break;
                case "Ano":
                    albums = albums.OrderBy(s => s.Ano);
                    break;
                case "ano_desc":
                    albums = albums.OrderByDescending(s => s.Ano);
                    break;
                case "Artista":
                    albums = albums.OrderBy(s => s.Artista);
                    break;
                case "artista_desc":
                    albums = albums.OrderByDescending(s => s.Artista);
                    break;
                case "Editora":
                    albums = albums.OrderBy(s => s.Editora);
                    break;
                case "editora_desc":
                    albums = albums.OrderByDescending(s => s.Editora);
                    break;
                default:
                    albums = albums.OrderBy(s => s.Ano);
                    break;
            }
            return View(albums.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Albums/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Artista = new SelectList(db.Artistas, "idArtista", "Nome");
            ViewBag.Editora = new SelectList(db.Editoras, "idEditora", "Nome");
            return View();
        }

        // POST: Albums/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idAlbum,Nome,Artista,Ano,Editora")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Artista = new SelectList(db.Artistas, "idArtista", "Nome", album.Artista);
            ViewBag.Editora = new SelectList(db.Editoras, "idEditora", "Nome", album.Editora);
            return View(album);
        }

        // GET: Albums/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.Artista = new SelectList(db.Artistas, "idArtista", "Nome", album.Artista);
            ViewBag.Editora = new SelectList(db.Editoras, "idEditora", "Nome", album.Editora);
            return View(album);
        }

        // POST: Albums/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAlbum,Nome,Artista,Ano,Editora")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Artista = new SelectList(db.Artistas, "idArtista", "Nome", album.Artista);
            ViewBag.Editora = new SelectList(db.Editoras, "idEditora", "Nome", album.Editora);
            return View(album);
        }

        // GET: Albums/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MusicRepo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MusicRepo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">
            <img src="~/Imagens/logo_small.png" alt="Logo MusicRepo" align="middle" />
            MusicRepo
        </a>
        <!--
            <div class="collapse navbar-collapse" id="navbarColor01">
            -->
            <ul class="navbar-nav mr-auto">
                <!-- @Html.ActionLink("MusicRepo ESII", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) -->
                <li class="nav-item">
                    <a class="nav-link" href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Albums">Albuns</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Artistas">Artistas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Editoras">Editoras</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Festivals">Festivais</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Musicas">Musicas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Home/Contact">Contacto</a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        <!--
        </div>
            -->
    </nav>

    <!--<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Início", "Index", "Home")</li>
        <li>@Html.ActionLink("Albuns", "Index", "Albums")</li>
        <li>@Html.ActionLink("Artistas", "Index", "Artistas")</li>
        <li>@Html.ActionLink("Editoras", "Index", "Editoras")</li>
        <li>@Html.ActionLink("Festivais", "Index", "Festivals")</li>
        <li>@Html.ActionLink("Musicas", "Index", "Musicas")</li>
        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
        <li>@Html.ActionLink("Contactos", "Contact", "Home")</li>
    </ul>
    </div> -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MusicRepo - IPVC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>